name: 'openbci-IndexNow'

on:
  schedule:
    # 每天北京时间上午 10:00 自动运行 (UTC 2:00)
    - cron: '0 2 * * *'
  workflow_dispatch: # 允许你在 GitHub 页面上手动点击按钮立即触发

jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: indexnow-action
        uses: bojieyang/indexnow-action@v3
        with:
          sitemap-location: 'https://openbci-cn.com/sitemap.xml'
          key: ${{ secrets.INDEXNOWOPENBCI }}
